name: _Deploy Code (sh)
# Workflow triggers -- modify accordingly as needed, defaults to manually triggered.
# Comments include documentation for most commonly used triggers for code activity.
on:
  workflow_call:
    secrets:
      ACQUIA_API_KEY:
        required: true
      ACQUIA_API_SECRET:
        required: true
      PRIVATE_SSH_KEY:
        required: true
jobs:
  deploy_code:
    name: Deploy Code
    runs-on:  ubuntu-latest
    env:
      COMPOSER_MEMORY_LIMIT: -1
      DRUPAL_ROOT: ./docroot
      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Get branch name (merge)
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Show branch name being used for this workflow.
        run: echo ${{ env.BRANCH_NAME }}
      - name: Execute a deployment
        env:
          ACQUIA_API_KEY: ${{ env.ACQUIA_API_KEY }}
          ACQUIA_API_SECRET: ${{ env.ACQUIA_API_SECRET }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          echo ${{ env.BRANCH_NAME }}
          echo "----------------------------------------------"
          exit 1;