name:  Run Tests on Code
on:
  # Manually trigger a workflow
  workflow_dispatch:
  # Trigger a workflow on commits, to the branches listed below.
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'maintenance/*'
      - 'hotfix/*'
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'maintenance/*'
      - 'hotfix/*'
jobs:
  expose_contexts_of_run:
    runs-on:  ubuntu-latest
    env:
      COMPOSER_MEMORY_LIMIT: -1
      DRUPAL_ROOT: ./docroot
      # Secrets are passed from the calling workflow and must be set into
      # environment variables to be used.  This is a requirement for
      # secrets, as the use of those is limited in scope and not normally
      # accessible unless explicitely passed.  Since these are encrypted
      # the calling workflow (which must have access to the secrets to be
      # able to pass them), will pass in the unencrypted values stored in
      # those secrets.  However, because the source of those values is
      # Github repository or organization level secrets, they cannot be
      # viewed in the Actions logs by dumping the envionment variables, they
      # are displayed as "****" values instead.
      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      # Set for debugging purposes.
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v4
      - name: Get branch name (merge)
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Show branch name being used for this workflow.
        run: echo ${{ env.BRANCH_NAME }}
      - name: Provide information about the contexts of the workflow run,
        env:
          ACQUIA_API_KEY: ${{ env.ACQUIA_API_KEY }}
          ACQUIA_API_SECRET: ${{ env.ACQUIA_API_SECRET }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          ## Set for debugging purposes
          GITHUB_CONTEXT: ${{ env.GITHUB_CONTEXT }}
        run: |
          ## Uncomment the following two lines for debugging and troubleshooting failed builds.
          echo "$GITHUB_CONTEXT"
          echo "${{ github.ref }}"
          exit 0;
  coding_standards_checks:
    uses: ./.github/workflows/coding-standards-checks.yml
  phpstan_static_analysis:
    uses: ./.github/workflows/phpstan-static-analysis.yml
  yaml_lint:
    uses: ./.github/workflows/yaml-lint.yml
  test_site_install:
    uses: ./.github/workflows/test-site-installation.yml
  dry_run_deployment:
    uses: ./.github/workflows/dry-run-deployment.yml
    secrets:
      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}